### ISSUE TITLE
are you still active?

### ISSUE THREAD

**Issue by DavidRPatton** [arke-industries/arke-industries.github.io#1]
Is anyone there? Does anyone use this game anymore? Is it open source? Im creating a text based spaceship game like TDZK.net (this is closed now) and like www.seinfinium.net. I want to do something more with the planets and im looking for some code to use as an example.

Talking about The Fall

squishysbusiness@gmail.com

**Comment by Arke64** [comment]
Unfortunately the source code for The Fall isn't available. Even so, it was written a long time ago and it is not suitable as a reference or example code. It'd only lead you further astray. We wish you luck, though.

**Comment by alteron808** [comment]
I'll also add that if you're after a browser based strategy game like The Fall was (or its contemporaries like Nationstates, Cyber Nations, or Lunar Wars), then implementation is relatively straightforward since you can make a web application using something like MVC. An online storefront and a web game share most of their backend in common after all, the main difference is what you do with the data and what you write to the database (instead of account name and shipping address, for example, a game might store player name and player starship strength, and use those for calculation in battles).

I'd start by going through the latest .NET MVC tutorial: https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/start-mvc?view=aspnetcore-2.2&tabs=visua

Once you have a feel for how Models, Views, and most importantly Controllers (for context, The Fall had controllers like WarController, MarketController, PlayerController) then you'll have a good sense of how you want to build the logic of the game you're after. 

Best of luck!
